service: notification-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: arn:aws:ses:*

functions:
  sendEmail:
    handler: src/handlers/sendEmail.handler

custom:
  bundle:
    linting: false
