service: notification-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - sqs:ReceiveMessage
      Resource:
        - arn:aws:ses:*
        - ${self:custom.mailQueue.arn}

resources:
  Resources:
    MailQueue: ${file(./src/resources/MailQueue.yml):MailQueue}
  Outputs:
    MailQueueArn: ${file(./src/resources/MailQueue.yml):Outputs.MailQueueArn}
    MailQueueUrl: ${file(./src/resources/MailQueue.yml):Outputs.MailQueueUrl}

functions:
  sendEmail:
    handler: src/handlers/sendEmail.handler
    events:
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1
custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue
  bundle:
    linting: false
